import pytest

from app.ingest import IngestError, ingest
from app.schemas import Vendor

# Synthetic data only — genotypes are made up.
HEADER = (
    "# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024\n"
    "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)


def _file(*rows: str) -> bytes:
    return (HEADER + "".join(r + "\n" for r in rows)).encode()


def test_parses_valid_file():
    records = ingest(_file(
        "rs0000001\t1\t82154\tAA",
        "rs0000002\tX\t2700157\tG",
        "i0000003\tMT\t16519\t--",
        "rs0000004\t22\t1000\tDI",
    ))

    assert len(records) == 4
    assert records[0].rsid == "rs0000001"
    assert records[0].position == 82154
    assert records[1].genotype == "G"
    assert all(r.vendor == Vendor.TWENTYTHREE_AND_ME for r in records)


def test_is_deterministic():
    data = _file("rs0000001\t1\t82154\tAA", "rs0000002\t2\t500\tCT")
    assert ingest(data) == ingest(data)


@pytest.mark.parametrize(
    ("rows", "message"),
    [
        ((), "no genotype records"),
        (("rs0000001\t1\t82154",), "expected 4"),
        (("rs0000001\t1\tabc\tAA",), "not a number"),
        (("rs0000001\t99\t82154\tAA",), "invalid chromosome"),
        (("rs0000001\t1\t82154\tAZ",), "invalid genotype"),
        (("rs0000001\t1\t82154\tAA", "rs0000001\t1\t82154\tAA"), "duplicate"),
    ],
)
def test_rejects_bad_files(rows, message):
    with pytest.raises(IngestError, match=message):
        ingest(_file(*rows))


def test_truncated_last_line_is_rejected():
    data = _file("rs0000001\t1\t82154\tAA") + b"rs0000002\t1\t9"
    with pytest.raises(IngestError, match="expected 4"):
        ingest(data)
